### ISSUE TITLE
Integrate membership purchase flow

### ISSUE THREAD

**Issue by rphi** [compsoc-edinburgh/website#35]
So I just tried to put the membership flow into a modal with an iframe. Didn't work fantastically because a) EUSA's website is broken and b) EUSA's small-screen version of their website is broken. Also I'm concerned that I haven't been given any HTTPS warnings but hey, if it's good enough for EUSA?

![2017-07-28 19 20 39](https://user-images.githubusercontent.com/8237136/28731215-f5bee142-73ca-11e7-8486-6920d21addfb.gif)

It's fair to say though that their flow is terrible, so if we could make it nicer or maybe even do something semi in-house: Stripe's "checkout" widget appears to just be an embeddable with all the backend and payment details being handled by their API. Although that could cause us to walk on a slightly fine line legally...? 

<img width="458" alt="screen shot 2017-07-28 at 19 28 16" src="https://user-images.githubusercontent.com/8237136/28731351-701a04a8-73cb-11e7-82de-361129de426b.png">

If people think this could be worth doing I can look into it in more detail, but I wouldn't be surprised if the answer is a flat no.

**Comment by qaisjp** [comment]
Great idea, this is very promising.

I'm interested in moving the online purchase to our systems. We have to inform EUSA about memberships anyway, so we can important purchases through our system that way.

Online memberships through the EUSA system goes to the EUSA bank account, which we do not use (we move funds in there to our external bank account). If we have our own online membership purchase flow we can keep money in our bank account rather than having to continually deal with the EUSA bank account.

We have a CompSoc server if any support is required server side. It's worth getting the input from our techsec @hreeder — what do you think, Harry?

**Comment by rphi** [comment]
No server side is needed, got a test flow up and running already using the example on the site and one of their test card numbers - just trying to integrate with Bootstrap buttons and modals. I'm guessing we'd want to take their addresses for identity verification? (by default it is just emails)

**Comment by qaisjp** [comment]
Okies. 

There are a couple form fields we need to take — are addresses a simple Stripe option or do you get the opportunity to add custom form fields?

The fields that come to mind are:
- personal email (default)
- **if student membership**: matriculation number (if ed.ac.uk), uni email (if non ed.ac.uk)
- academic year: ug1/ug2/ug3/ug4/ug5/msc/nonstudent
- cv field (a url, and if possible, file upload)

I don't think addresses are necessary.

-------

The following notes are not a big deal since we can assume interested members are honest about being a student, but I'm mentioning it here anyway:
- the old system blocked off the "student" tier for those not logged in with EASE
- non-ed.ac.uk-students could buy student membership by showing up in person with student ID
- non-students with the new system would be able to pay student prices without being a student

-------

Also, the "Join" page up there is a css hack that bypasses their sanitisation:

```
<div style="position:fixed; top: 0; padding-top: 5%; left: 0; width: 100%; height: 100%; text-align: center; z-index:99999; background: white;">
<a href="http://comp-soc.com"><img alt=" " style="max-width: 500px; width: 100%; padding-left:10px; padding-right:10px; display:block; margin:auto;" src="/pageassets/societies/society/compsoc/join/compsoc-horizontal.png" /></a>
<br />

<p>Interested in becoming&nbsp;a member of <a href="http://comp-soc.com">CompSoc</a>? We&#39;d love to have you.</p>

<p>For students (of any university), membership is &pound;4. Otherwise, it costs &pound;8.</p>

<p>You may also register in person at any of our STMUs.</p>

<!-- Developer note. Actually uses the { join } widget -->
<!-- <p>{join}</p> -->

<br />
<a href="https://www.eusa.ed.ac.uk/login/?redirect=/societies/society/compsoc/join/">Make sure you're logged in before adding to basket.</a>
<br />
<input type="submit" name="ctl00$join$rptJoin$ctl01$btnAdd" value="Add student membership to basket" id="ctl00_join_rptJoin_ctl01_btnAdd" class="button" />
<br />
<input type="submit" name="ctl00$join$rptJoin$ctl02$btnAdd" value="Add non-student membership to basket" id="ctl00_join_rptJoin_ctl01_btnAdd" class="button" />
<br />
<a href="https://www.eusa.ed.ac.uk/shop/reviewbasket/">Then review your basket.</a>


</div>
```

**Comment by rphi** [comment]
Stripe has an option to request addresses, or just a postal code, but other than that their prebuilt flow doesn't include anything else. However, it does throw out a token after the payment has been processed, which we could then take into our own "additional info" survey form? Ultimately if they don't fill it in, someone can just ask them before they get their card? We could verify based on email, last 4 digits of card no and post code? (get Stripe to throw out a report of any new memberships)

Personally I'd be uncomfortable taking too much personal info (e.g. full addresses and cvs) into our database, it's just not worth the risk. All the card details never leave Stripe so we don't have to worry about that.

**Comment by qaisjp** [comment]
I see. Good point about the card collection student verification.

Right now online memberships are just lost in the abyss (until we find them), and we have to be careful about importing them to our internal database (ahem, just a Google Spreadsheet).

Even if we don't get the extra data, it's okay, because we still get:
- easier online registration (current hack is shit)
- better theming (because we put stripe on our website)
- literally no more need for the EUSA website (there's a nice hack to redirect the compsoc page on EUSA to the compsoc website)

I look forward to see what you come up with :)

**Comment by rphi** [comment]
Lots of nice things in the PR 😁 ⬆️

**Comment by CraigSnowden** [comment]
Hello. Make sure you take into account the fees. 

With EUSA at least you don't have to pay any commission

**Comment by qaisjp** [comment]
Ah crap, that's a thing isn't it :/

**Comment by qaisjp** [comment]
chargebacks may also be a thing to worry about too :/

**Comment by rphi** [comment]
Eeh okay so Stripe's fees aren't fantastic - I thought they had a micro transactions tier, but apparently I was thinking of PayPal instead...

Stripe: 
<img width="417" alt="screen shot 2017-07-29 at 11 08 50" src="https://user-images.githubusercontent.com/8237136/28743972-9dad8178-744e-11e7-9dae-903d50dd2191.png">

Although they do claim to have a separate (unpublished) [non-profit fee schedule](https://support.stripe.com/questions/does-stripe-offer-a-fee-discount-for-non-profit-organizations).

PayPal on the other hand has a micropayments tier if your sales average under £5 which is 5% + 5p per transaction, or 3.4% + 20p per transaction for larger payments. If we register as non-profit/charity then it's 1.4% + 20p per transaction.

But yeah, very valid point - I had made the assumption that EUSA were using a payments gateway so the current method also incurred a fee.

**Comment by rphi** [comment]
PayPal would probably be easier too as you wouldn't need any backend:
https://developer.paypal.com/demo/checkout/#/pattern/styles

**Comment by neanias** [comment]
Braintree is where it's at

**Comment by rphi** [comment]
Braintree looks nice, but what would be the advantage over PayPal's normal express checkout (assuming we get the discounted non-profit or micro transaction rate)? It's a service I've heard of but never had much to do with.

**Comment by hreeder** [comment]
The biggest hole I'm seeing is where the data goes after payment has been
completed. If it's paypal, do we just get an email with text to the effect
of "{person} has paid for {product}"?

If so, do they offer some kind of callback service that would allow us to
host a backend service where we receive the data which we can then process?
I'd not be thinking anything huge, probably just a small docker service
that takes the input from {payment_provider} and outputs to wherever we're
storing the data.

In that event, I'd happily take care of the infrastructure around running
said service, and inbound routing to the right service.

**Comment by rphi** [comment]
From my experiences of Stripe, you can generate reports of payments from their management backend, but it also did give a token which we would have to process on a CompSoc server, so then some information can be siphoned off then as well.

I think PayPal's express checkout also passes back an object with tokenised payment details, along with the status that we could then AJAX back to a database somewhere.

**Comment by bnelo12** [comment]
How is this issue coming along. I have noticed the "Become a member" button in community is broken on master.

**Comment by qaisjp** [comment]
fixed in 6317be4

**Comment by rphi** [comment]
Right, so I'm going to go ahead with finishing off the stripe implementation - its going to cost no more than 25p per transaction for the standard membership (less if we get approved for their top-secret non-profit pricing), and stripe is nicer than PayPal. Heck, could we get them to sponsor us in exchange for no fees?

**Comment by neanias** [comment]
I think it would be better to have their sweet, sweet cash than just give us no fees in terms of sponsorship.

**Comment by rphi** [comment]
I mean, that would be better, also slightly less probable?

**Comment by qaisjp** [comment]
Stripe would be a cool company to sponsor us. I'll get in touch with them.

**Comment by qaisjp** [comment]
Also, what if we charge people that use the online system the extra 30p?

**Comment by rphi** [comment]
http://www.bbc.co.uk/news/business-40648641

**Comment by neanias** [comment]
Are we allowed to do that? Where’s Captain Bureaucracy when you need him? Paging @craigsnowden...

**Comment by rphi** [comment]
Also stickers pls

**Comment by qaisjp** [comment]
Heads up. https://www.eusa.ed.ac.uk/societies/society/compsoc/ and https://www.eusa.ed.ac.uk/societies/society/compsoc/join have both been updated, so if we don't do the Stripe stuff, the new `/join` should be useful (if need be I can style this specifically for the pop-up modal — I think I can make the basket link target the parent iframe)

**Comment by ettolrach** [comment]
There is no need to keep this open, since membership is free. Plus, opening a new tab isn't that annoying, using an iframe would leave us potentially vulnerable.
